// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Supabase's pooled connection cannot host the shadow database that
    // `migrate dev` needs; point this at a direct connection.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
